                        -- intergers  google mysql integer types
-- tinyint 1b [-128,127]
-- Undesigned tinyint [0,255] particular useful for value of people's age
-- SMALLINT 2b [-32k,32k]
-- MEDIUMINT 3b [-8M,8M]
-- INT 4b [-2B,2B]
-- BIGINT 8b [-9Z,9Z]